name: Check PR to main for blocking comments

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - review_requested
      - synchronize
    branches:
      - main

jobs:
  pullrequest_to_main:
    runs-on: linux-runners

    steps:
      # get changed files from PR
      - name: Checkout PR head ref
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get changed files
        id: changed-files
        uses: actions/changed-files@v42
        with:
          files: files/**
